# Generated by Django 5.2.3 on 2025-06-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='email',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
