# Generated by Django 5.2.3 on 2025-06-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_cart_email_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
    ]
