# Generated by Django 5.2.3 on 2025-06-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_cart_session_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
